project_id = "tkrcdxkdfjeupbdlbcfz"

[functions.ai-local-edit]
verify_jwt = true
request_timeout = 120

[functions.render-page]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.robots]
verify_jwt = false

[functions.submit-lead]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.ai-edit-page]
verify_jwt = true
request_timeout = 480

[functions.generate-email-template]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.company-settings-ai-guide]
verify_jwt = true

[functions.bulk-update-templates]
verify_jwt = true

[functions.validate-and-fix-html]
verify_jwt = true

[functions.send-makecom-webhook]
verify_jwt = true

[functions.database-webhook]
verify_jwt = false

[functions.generate-color-palette]
verify_jwt = true